# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"\xae\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1f\n\x05genre\x18\x04 \x01(\x0e\x32\x10.book.Book.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"?\n\x05Genre\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07\x46ICTION\x10\x01\x12\x0f\n\x0bNON_FICTION\x10\x02\x12\x0b\n\x07ROMANCE\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=21
  _BOOK._serialized_end=195
  _BOOK_GENRE._serialized_start=132
  _BOOK_GENRE._serialized_end=195
# @@protoc_insertion_point(module_scope)
