# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryItem.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import book_pb2 as book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13inventoryItem.proto\x12\x04\x62ook\x1a\nbook.proto\"\xaf\x01\n\rInventoryItem\x12\x18\n\x10inventory_number\x18\x01 \x01(\t\x12\x1a\n\x04\x62ook\x18\x02 \x01(\x0b\x32\n.book.BookH\x00\x12*\n\x06status\x18\x03 \x01(\x0e\x32\x1a.book.InventoryItem.Status\"/\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\r\n\tAVAILABLE\x10\x01\x12\t\n\x05TAKEN\x10\x02\x42\x0b\n\titem_typeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryItem_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INVENTORYITEM._serialized_start=42
  _INVENTORYITEM._serialized_end=217
  _INVENTORYITEM_STATUS._serialized_start=157
  _INVENTORYITEM_STATUS._serialized_end=204
# @@protoc_insertion_point(module_scope)
