# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import book_pb2 as book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x04\x62ook\x1a\nbook.proto\"%\n\x12\x43reateBookResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t2w\n\x10InventoryService\x12\x34\n\nCreateBook\x12\n.book.Book\x1a\x18.book.CreateBookResponse\"\x00\x12-\n\x07GetBook\x12\x14.book.GetBookRequest\x1a\n.book.Book\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKRESPONSE._serialized_start=35
  _CREATEBOOKRESPONSE._serialized_end=72
  _GETBOOKREQUEST._serialized_start=74
  _GETBOOKREQUEST._serialized_end=104
  _INVENTORYSERVICE._serialized_start=106
  _INVENTORYSERVICE._serialized_end=225
# @@protoc_insertion_point(module_scope)
